<!DOCTYPE html><html><head><meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1" class="next-head"/><meta charSet="utf-8" class="next-head"/><title class="next-head">Utop&#x27;s Blog</title><link rel="preload" href="https://www.ffutop.com/blog/_next/static/KZWxx6ur1oSf8xr-9UZXm/pages/post.js" as="script"/><link rel="preload" href="https://www.ffutop.com/blog/_next/static/KZWxx6ur1oSf8xr-9UZXm/pages/_app.js" as="script"/><link rel="preload" href="https://www.ffutop.com/blog/_next/static/runtime/webpack-8ed9452df514b4d17d80.js" as="script"/><link rel="preload" href="https://www.ffutop.com/blog/_next/static/chunks/commons.7e5e68e72610ac3a4255.js" as="script"/><link rel="preload" href="https://www.ffutop.com/blog/_next/static/chunks/styles.f3603d0a56c82c4f5e78.js" as="script"/><link rel="preload" href="https://www.ffutop.com/blog/_next/static/runtime/main-fd73dbd6f398b7b886ec.js" as="script"/><link rel="stylesheet" href="https://www.ffutop.com/blog/_next/static/css/commons.736184b0.chunk.css"/><link rel="stylesheet" href="https://www.ffutop.com/blog/_next/static/css/styles.55a7521e.chunk.css"/></head><body><div id="__next"><header class="component-header"><h1 class="title">ffutop</h1><ul class="nav-items"><li><a href="/blog/index">博客</a></li><li><a href="/blog/archives">归档</a></li><li><a href="/blog/tags">标签</a></li><li><a href="/blog/about">关于</a></li></ul></header><div><main class="main"><div class="page-post"><div><p>历时一周总算把导致服务大量 <code>CLOSE_WAIT</code> 的原因给找到了。打印任务调用栈果然的必备手段啊！</p>
<h2>问题描述</h2>
<p>Python 服务 A，用于接收心跳包确认其他服务是否存活。其他服务每 5 分钟向 A 发送一次心跳包；总计 &#x3C; 100 个其他服务。</p>
<ul>
<li>05-11 19:30 ，首次出现 Python 服务大量 <code>CLOSE_WAIT</code>，至 13 日发现，总计 10k 左右 <code>CLOSE_WAIT</code> 的 TCP 连接。05-13 15:30 通过运维平台重新部署...</li>
<li>05-14 16:30 ，再次出现。19:30 手动重启。</li>
<li>其间给 Python 服务 A 添加了打印调用栈的模块 <a href="https://pypi.org/project/pdbx/">pdbx</a>，通过运维平台重新部署</li>
<li>05-17 19:00 ，再次出现。等待打印调用栈，不小心杀掉了服务...</li>
<li>05-19 14:30 ，重现。</li>
<li>05-20 08:30 ，查找原因，解决问题。</li>
</ul>
<p>由于不是本人负责的服务，于 16 日凭兴趣开始有限介入，协助排查。现将排查流程一一记述，给自己和大家未来排查问题提供一个借鉴。</p>
<h2>问题探究</h2>
<h3>CLOSE_WAIT 现象梳理</h3>
<p>16 日拿到的信息只有前两次问题记录。</p>
<p><img src="http://img.ffutop.com/82B074FB-68FF-4A21-B664-A557FECBB2DF.png"></p>
<p>大量 <code>CLOSE_WAIT</code> 状态的 TCP 连接，<code>Recv-Q</code> 数据大小平均在 300 Bytes 左右。对比实际的 HTTP 包大小，恰好是一次 HTTP Request 请求大小。同时参考 Nginx 打印的日志，确定是一次 HTTP 请求的数据包大小，同时都以 Timeout 为结束。</p>
<p>OK，简单地建立起了第一个印象，TCP 断开连接的 FIN 包由 Nginx 请求超时后发起(<code>proxy_read_timeout 300s</code>) 。A 服务所在的 Linux 机器接收到 FIN 包，并由内核线程直接将套接字状态置位为 <code>CLOSE_WAIT</code> 。</p>
<p>A 服务没意识到 FIN 包？当然，接收了 FIN 包之后，再回应 ACK 包，这“四次挥手”的第二个数据包并不会被 A 服务所认知，而是由内核的 <code>[ksoftirqd]</code> 内核线程直接处理。看下内核处理 FIN 包的代码 (from <code>net/ipv4/tcp_input.c</code>)。</p>
<pre><code class="language-c">/*
 * 处理 FIN 包
 *
 * 如果当前套接字是 ESTABLISHED 状态，则接收 FIN 包，进入 CLOSE-WAIT
 * 状态 
 * ...
 */
void tcp_fin(struct sock *sk)
{
    struct tcp_sock *tp = tcp_sk(sk);

    inet_csk_schedule_ack(sk);

    sk->sk_shutdown |= RCV_SHUTDOWN;
    sock_set_flag(sk, SOCK_DONE);

    switch (sk->sk_state) {
    case TCP_SYN_RECV:
    case TCP_ESTABLISHED:
        /* 当前为 ESTABLISHED 状态，进入 CLOSE_WAIT */
        tcp_set_state(sk, TCP_CLOSE_WAIT);
        inet_csk(sk)->icsk_ack.pingpong = 1;
        break;

    // ... more omitted 

    }

    // ... more omitted 
}
</code></pre>
<p>更多关于网络相关的内核实现请参考 <a href="https://www.ffutop.com/2019-01-15-understand-Kernel-8/">理解 Linux Kernel (8) - 网络</a></p>
<p>再结合 <code>Recv-Q</code> 恰好等于一次完整 HTTP 请求的条件，可以认识到 Python 线程根本没有 <code>recv</code> 请求数据。更别提意识到远端发出来 FIN 包。</p>
<p>到此为止，由前两次的问题得到的线索，只能认为 Python 服务 A 的所有工作线程都在哪段代码阻塞了。而我所能认知的唯一条件就是事务死锁（当然，我犯了比较大的错误）。事实上看代码根本就没有任何死锁代码。暂时无果。</p>
<h3>打印线程调用栈 (一次失败的尝试)</h3>
<p>集成了调用栈打印工具 <code>pdbx</code> （强烈安利，我们老大写的，很好用的工具）之后，按理说 18 日解决问题是非常容易的。</p>
<p>结果按照文档的描述，使用 <code>kill -30 &#x3C;PID></code> ，Python 服务进程莫名挂掉。功亏一篑啊。后来查看源码发现 <code>pdbx</code> 重定义了 <code>USR1</code> 信号的处理函数。T_T Linux x86 平台下，对应的信号值为 10. </p>
<hr>
<p>额外地穿插一点信号相关的内容。<code>signal</code> 是一种异步处理机制，一般由执行流在退出内核态回到用户态之前 Check 当前任务的信号队列（为什么会主动 check 呢？当然是内核代码提前写好的流程），并主动针对获得的信号调用对应的信号处理函数。</p>
<p>可怕的是，之前竟然一直没有意识到信号值在不同的 CPU 架构下是不同的。USR1 在 x86 平台下是 10，在 平台下是 30 。而 BSD 又与 Linux 的编号方案不同。</p>
<blockquote>
<p>Linux  supports  the standard signals listed below.  Several signal numbers are architecture-dependent, as indicated in the "Value" column.  (Where three values are given, the first one is usually valid for alpha and sparc, the middle one for x86, arm, and most other architectures, and the last one for mips.  (Values for parisc are not shown; see the Linux kernel source for signal numbering on that architecture.)  A dash (-) denotes that a signal is absent on the corresponding architecture.
Linux 支持的标准信号如下。一些信号值是平台相关的（Value 列，第一个值用于 alpha 和 sparc 平台，中间的值用于 x86、arm 和大量其他架构，最后一个值用于 mips 平台）</p>
<pre><code class="language-sh">Signal     Value     Action   Comment
----------------------------------------------------------------------
SIGHUP        1       Term    Hangup detected on controlling terminal or death of controlling process
SIGINT        2       Term    Interrupt from keyboard
SIGQUIT       3       Core    Quit from keyboard
SIGKILL       9       Term    Kill signal
SIGUSR1   30,10,16    Term    User-defined signal 1
SIGUSR2   31,12,17    Term    User-defined signal 2
</code></pre>
</blockquote>
<p>总结下，最靠谱的写法就是直接用信号的字符描述啦。<code>kill -s USR1 &#x3C;PID></code></p>
<hr>
<h3>打印线程调用栈</h3>
<p>19 日下午再次重现，等到 20 日周一上班，总是成功地拿到了线程的调用栈。</p>
<pre><code>"CP Server Thread-10" tid=139694658537216
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at conn.communicate()(wsgiserver2.py:1532)
    ... more omitted
    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)
    at return self.query(qout, processed=True)(db.py:720)
    at self._db_execute(db_cursor, sql_query)(db.py:680)
    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)
    at out.write(x)(webapi.py:512)

"CP Server Thread-9" tid=139694666929920
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at conn.communicate()(wsgiserver2.py:1532)
    ... more omitted 
    at apps = list(db.select('application', vars, where='name=$name'))(xxx.py:149)
    at return self.query(qout, processed=True)(db.py:720)
    at self._db_execute(db_cursor, sql_query)(db.py:680)
    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)
    at out.write(x)(webapi.py:512)

"MainThread" tid=139695478638400
    at app.run()(xxx.py:326)
    at return wsgi.runwsgi(self.wsgifunc(*middleware))(application.py:341)
    at return httpserver.runsimple(func, server_addr)(wsgi.py:59)
    at server.start()(httpserver.py:177)
    at self.tick()(wsgiserver2.py:1956)
    at s, addr = self.socket.accept()(wsgiserver2.py:2008)
    at sock, addr = self._sock.accept()(socket.py:202)
    at pystack()(pdbx.py:181)
    at for filename, lineno, _, line in traceback.extract_stack(stack):(pdbx.py:169)

... omit CP Server Thread-1 / Thread-2 / Thread-6 / Thread-7 / Thread-8
... same as other thread

"CP Server Thread-4" tid=139695180908288
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at conn.communicate()(wsgiserver2.py:1532)
    ... more omitted 
    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)
    at return self.query(qout, processed=True)(db.py:720)
    at self._db_execute(db_cursor, sql_query)(db.py:680)
    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)
    at out.write(x)(webapi.py:512)

"APScheduler" tid=139695219828480
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at self.__target(*self.__args, **self.__kwargs)(threading.py:765)
    at self._event.wait(wait_seconds)(blocking.py:28)
    at self.__cond.wait(timeout, balancing)(threading.py:622)
    at waiter.acquire()(threading.py:339)

"CP Server Thread-3" tid=139695189300992
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at conn.communicate()(wsgiserver2.py:1532)
    ... more omitted 
    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)
    at return self.query(qout, processed=True)(db.py:720)
    at self._db_execute(db_cursor, sql_query)(db.py:680)
    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)
    at out.write(x)(webapi.py:512)

"CP Server Thread-5" tid=139695172515584
    at self.__bootstrap_inner()(threading.py:785)
    at self.run()(threading.py:812)
    at conn.communicate()(wsgiserver2.py:1532)
    ... more omitted 
    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)
    at return self.query(qout, processed=True)(db.py:720)
    at self._db_execute(db_cursor, sql_query)(db.py:680)
    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)
    at out.write(x)(webapi.py:512)
</code></pre>
<p>OK，总计 10 个工作线程，全都阻塞在 <code>out.write(x)</code> ，多次打印调用栈结果相同。基本可以断定是 <code>write</code> 方法出了问题了。不过直到这个时候，都还是深陷在死锁原因中无法自拔（还是接触得太少了）。</p>
<p>虚度半个多钟... 后看代码了解到，其准备将 SQL 执行结果打印到标准错误。</p>
<pre><code class="language-python">def _debugwrite(x):
    try:
        out = ctx.environ['wsgi.errors']
    except:
        out = sys.stderr
    out.write(x)
debug.write = _debugwrite
</code></pre>
<p>果断去查看 Python 服务的文件描述符 <code>lsof -p &#x3C;PID></code> / <code>ls -al /proc/&#x3C;PID>/fd</code> 。总算见着可信的证据了。</p>
<pre><code>> lsof -p &#x3C;PID>
python  139756 sysop    0r  FIFO     0,9       0t0 5210639 pipe
python  139756 sysop    1w   REG   253,1      5187 1188500 /home/www/wwwroot/logs/eswitch-console.9999.log
python  139756 sysop    2w  FIFO     0,9       0t0 5210641 pipe
python  139756 sysop    3u  IPv4 5210787       0t0     TCP 10.1.5.60:65442->10.1.6.104:mysql (ESTABLISHED)
python  139756 sysop    4r  FIFO     0,9       0t0 5210774 pipe
python  139756 sysop    5w  FIFO     0,9       0t0 5210774 pipe
python  139756 sysop    6r  FIFO     0,9       0t0 5210778 pipe
python  139756 sysop    7w  FIFO     0,9       0t0 5210778 pipe
python  139756 sysop    8u  IPv4 5210788       0t0     TCP *:distinct (LISTEN)
python  139756 sysop    9u  IPv4 5226722       0t0     TCP localhost:distinct->localhost:26032 (CLOSE_WAIT)
python  139756 sysop   10u  IPv4 5226858       0t0     TCP localhost:distinct->localhost:26052 (CLOSE_WAIT)
... more omitted
</code></pre>
<pre><code>> ls -al /proc/&#x3C;PID>/fd
lr-x------ 1 sysop sysop 64 May 20 13:47 0 -> pipe:[5210639]
l-wx------ 1 sysop sysop 64 May 20 13:47 1 -> /home/path/to/logs/xxx.log
l-wx------ 1 sysop sysop 64 May 20 13:47 2 -> pipe:[5210641]
lrwx------ 1 sysop sysop 64 May 20 13:47 3 -> socket:[5210787]
lr-x------ 1 sysop sysop 64 May 20 13:47 4 -> pipe:[5210774]
l-wx------ 1 sysop sysop 64 May 20 13:47 5 -> pipe:[5210774]
lr-x------ 1 sysop sysop 64 May 20 13:47 6 -> pipe:[5210778]
l-wx------ 1 sysop sysop 64 May 20 13:47 7 -> pipe:[5210778]
... more omitted
</code></pre>
<p>标准错误(fd = 2)指向了一个匿名管道（inode = 5210641）。但是找遍整个系统都没有这个匿名管道的读取方，只有写入方</p>
<pre><code class="language-sh">> sudo lsof | grep 5210641
bash      139747          sysop    2w     FIFO                0,9       0t0    5210641 pipe
python    139756          sysop    2w     FIFO                0,9       0t0    5210641 pipe
python    139756 139764   sysop    2w     FIFO                0,9       0t0    5210641 pipe
</code></pre>
<p>OK，合理的解释出现了。管道的缓冲区大小有限(经过测试是 64KB)，Python 服务在不断地向标准错误打印日志，从而导致匿名管道(inode = 5210641)的缓冲区数据不断积累，最终达到满的状态。这个过程大概需要一天多的心跳包才能积累得到。而系统调用 <code>write</code> 发现标准错误对应的文件已满，为等待 IO 就绪而陷入睡眠状态。同时，Main 线程在不断地 Accept 新的套接字的建立，而没有更多工作线程来处理新的请求，Nginx 因为连接超时直接发出来 FIN 包。最后，积累了几千/上万请求的 Python 服务也没法主动 close 已有的套接字（即 FIN,ACK 包因为没法发送而在本机不断积累 <code>CLOSE_WAIT</code> 状态的连接）</p>
<h3>重定向标准错误的原因</h3>
<p>至于为何会将标准错误重定向到一个匿名管道呢？百思不得其解，不过最后还是从应用负责人那儿得到了提示。新的发布方式采用了全新的启动命令:</p>
<pre><code class="language-sh">ssh -fn xx.xx.x.60 'cd /home/path/to/xxx ; python -u xxx.py 8080 >> /home/path/to/logs/xxx.log'
</code></pre>
<p>一看就能和前面的原因衔接，使用 ssh 直接调用命名，不会建立一个终端，由 ssh 远程命令启动的任务，其标准输入/输出/错误默认将会通过管道重定向的 ssh server 端，并通过网络传回发起的 ssh client 端。</p>
<p><em>以发起 <code>ssh -fn ...</code> 的机器为 xx.192，目标机器为 xx.60</em></p>
<pre><code class="language-plain">  xx.192                       |           xx.60
  -----------------------------+-------------------------------
                               | 
    ssh client                 |          ssh serve           python serve
  +------------+               |        +------------+       +-------------+
  | 0 | stdin  |               |        | y | pipe[a]| &#x3C;---> | 0 | pipe[a] |
  | 1 | stdout |               |        | z | pipe[b]| &#x3C;-+   | 1 | xxx.log |
  | 2 | stderr |               |        |   |        |   +-> | 2 | pipe[b] |
  | ...        |               |        | ...        |       | ...         |
  | x | sock   | &#x3C;--------------------> | w | sock   |       | ...         |
  +------------+               |        +------------+       +-------------+
</code></pre>
<p>Python 服务通过管道与 ssh serve 进行进程间交互，最终会将标准错误打印到 192 机器的标准输出/错误上（一般是终端，也就是我们将在终端上看到 Python 服务的错误日志）。而问题在于 ssh serve 任务被杀掉了，从而 <code>pipe[b]</code> 只能不断地向匿名管道写入数据，而没有任务读取数据，一天多时间也就将缓冲区写满了。</p>
<h2>总结</h2>
<p>到此为止，问题总算得到了圆满的解释，历时 5 天。最重要的就是通过调用栈定位代码阻塞的原因，否则就真是瞎找。对于匿名管道问题的发现、write 系统调用导致的线程睡眠，都是建立在调用栈信息之上的定向探究的过程。</p>
<pre><code class="language-plain">  __                    __                  
 / _| __ _ _ __   __ _ / _| ___ _ __   __ _ 
| |_ / _` | '_ \ / _` | |_ / _ \ '_ \ / _` |
|  _| (_| | | | | (_| |  _|  __/ | | | (_| |
|_|  \__,_|_| |_|\__, |_|  \___|_| |_|\__, |
                 |___/                |___/ 
</code></pre></div></div></main><footer class="footer">ffutop © <!-- -->2019<!-- -->, Powered by <a href="https://reactjs.org/">React</a> and <a href="https://nextjs.org/">Next.js</a></footer></div></div><script id="__NEXT_DATA__" type="application/json">{"dataManager":"[]","props":{"pageProps":{}},"page":"/post","query":{"content":"\u003cp\u003e历时一周总算把导致服务大量 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e 的原因给找到了。打印任务调用栈果然的必备手段啊！\u003c/p\u003e\n\u003ch2\u003e问题描述\u003c/h2\u003e\n\u003cp\u003ePython 服务 A，用于接收心跳包确认其他服务是否存活。其他服务每 5 分钟向 A 发送一次心跳包；总计 \u0026#x3C; 100 个其他服务。\u003c/p\u003e\n\u003cul\u003e\n\u003cli\u003e05-11 19:30 ，首次出现 Python 服务大量 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e，至 13 日发现，总计 10k 左右 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e 的 TCP 连接。05-13 15:30 通过运维平台重新部署...\u003c/li\u003e\n\u003cli\u003e05-14 16:30 ，再次出现。19:30 手动重启。\u003c/li\u003e\n\u003cli\u003e其间给 Python 服务 A 添加了打印调用栈的模块 \u003ca href=\"https://pypi.org/project/pdbx/\"\u003epdbx\u003c/a\u003e，通过运维平台重新部署\u003c/li\u003e\n\u003cli\u003e05-17 19:00 ，再次出现。等待打印调用栈，不小心杀掉了服务...\u003c/li\u003e\n\u003cli\u003e05-19 14:30 ，重现。\u003c/li\u003e\n\u003cli\u003e05-20 08:30 ，查找原因，解决问题。\u003c/li\u003e\n\u003c/ul\u003e\n\u003cp\u003e由于不是本人负责的服务，于 16 日凭兴趣开始有限介入，协助排查。现将排查流程一一记述，给自己和大家未来排查问题提供一个借鉴。\u003c/p\u003e\n\u003ch2\u003e问题探究\u003c/h2\u003e\n\u003ch3\u003eCLOSE_WAIT 现象梳理\u003c/h3\u003e\n\u003cp\u003e16 日拿到的信息只有前两次问题记录。\u003c/p\u003e\n\u003cp\u003e\u003cimg src=\"http://img.ffutop.com/82B074FB-68FF-4A21-B664-A557FECBB2DF.png\"\u003e\u003c/p\u003e\n\u003cp\u003e大量 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e 状态的 TCP 连接，\u003ccode\u003eRecv-Q\u003c/code\u003e 数据大小平均在 300 Bytes 左右。对比实际的 HTTP 包大小，恰好是一次 HTTP Request 请求大小。同时参考 Nginx 打印的日志，确定是一次 HTTP 请求的数据包大小，同时都以 Timeout 为结束。\u003c/p\u003e\n\u003cp\u003eOK，简单地建立起了第一个印象，TCP 断开连接的 FIN 包由 Nginx 请求超时后发起(\u003ccode\u003eproxy_read_timeout 300s\u003c/code\u003e) 。A 服务所在的 Linux 机器接收到 FIN 包，并由内核线程直接将套接字状态置位为 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e 。\u003c/p\u003e\n\u003cp\u003eA 服务没意识到 FIN 包？当然，接收了 FIN 包之后，再回应 ACK 包，这“四次挥手”的第二个数据包并不会被 A 服务所认知，而是由内核的 \u003ccode\u003e[ksoftirqd]\u003c/code\u003e 内核线程直接处理。看下内核处理 FIN 包的代码 (from \u003ccode\u003enet/ipv4/tcp_input.c\u003c/code\u003e)。\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-c\"\u003e/*\n * 处理 FIN 包\n *\n * 如果当前套接字是 ESTABLISHED 状态，则接收 FIN 包，进入 CLOSE-WAIT\n * 状态 \n * ...\n */\nvoid tcp_fin(struct sock *sk)\n{\n    struct tcp_sock *tp = tcp_sk(sk);\n\n    inet_csk_schedule_ack(sk);\n\n    sk-\u003esk_shutdown |= RCV_SHUTDOWN;\n    sock_set_flag(sk, SOCK_DONE);\n\n    switch (sk-\u003esk_state) {\n    case TCP_SYN_RECV:\n    case TCP_ESTABLISHED:\n        /* 当前为 ESTABLISHED 状态，进入 CLOSE_WAIT */\n        tcp_set_state(sk, TCP_CLOSE_WAIT);\n        inet_csk(sk)-\u003eicsk_ack.pingpong = 1;\n        break;\n\n    // ... more omitted \n\n    }\n\n    // ... more omitted \n}\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003e更多关于网络相关的内核实现请参考 \u003ca href=\"https://www.ffutop.com/2019-01-15-understand-Kernel-8/\"\u003e理解 Linux Kernel (8) - 网络\u003c/a\u003e\u003c/p\u003e\n\u003cp\u003e再结合 \u003ccode\u003eRecv-Q\u003c/code\u003e 恰好等于一次完整 HTTP 请求的条件，可以认识到 Python 线程根本没有 \u003ccode\u003erecv\u003c/code\u003e 请求数据。更别提意识到远端发出来 FIN 包。\u003c/p\u003e\n\u003cp\u003e到此为止，由前两次的问题得到的线索，只能认为 Python 服务 A 的所有工作线程都在哪段代码阻塞了。而我所能认知的唯一条件就是事务死锁（当然，我犯了比较大的错误）。事实上看代码根本就没有任何死锁代码。暂时无果。\u003c/p\u003e\n\u003ch3\u003e打印线程调用栈 (一次失败的尝试)\u003c/h3\u003e\n\u003cp\u003e集成了调用栈打印工具 \u003ccode\u003epdbx\u003c/code\u003e （强烈安利，我们老大写的，很好用的工具）之后，按理说 18 日解决问题是非常容易的。\u003c/p\u003e\n\u003cp\u003e结果按照文档的描述，使用 \u003ccode\u003ekill -30 \u0026#x3C;PID\u003e\u003c/code\u003e ，Python 服务进程莫名挂掉。功亏一篑啊。后来查看源码发现 \u003ccode\u003epdbx\u003c/code\u003e 重定义了 \u003ccode\u003eUSR1\u003c/code\u003e 信号的处理函数。T_T Linux x86 平台下，对应的信号值为 10. \u003c/p\u003e\n\u003chr\u003e\n\u003cp\u003e额外地穿插一点信号相关的内容。\u003ccode\u003esignal\u003c/code\u003e 是一种异步处理机制，一般由执行流在退出内核态回到用户态之前 Check 当前任务的信号队列（为什么会主动 check 呢？当然是内核代码提前写好的流程），并主动针对获得的信号调用对应的信号处理函数。\u003c/p\u003e\n\u003cp\u003e可怕的是，之前竟然一直没有意识到信号值在不同的 CPU 架构下是不同的。USR1 在 x86 平台下是 10，在 平台下是 30 。而 BSD 又与 Linux 的编号方案不同。\u003c/p\u003e\n\u003cblockquote\u003e\n\u003cp\u003eLinux  supports  the standard signals listed below.  Several signal numbers are architecture-dependent, as indicated in the \"Value\" column.  (Where three values are given, the first one is usually valid for alpha and sparc, the middle one for x86, arm, and most other architectures, and the last one for mips.  (Values for parisc are not shown; see the Linux kernel source for signal numbering on that architecture.)  A dash (-) denotes that a signal is absent on the corresponding architecture.\nLinux 支持的标准信号如下。一些信号值是平台相关的（Value 列，第一个值用于 alpha 和 sparc 平台，中间的值用于 x86、arm 和大量其他架构，最后一个值用于 mips 平台）\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-sh\"\u003eSignal     Value     Action   Comment\n----------------------------------------------------------------------\nSIGHUP        1       Term    Hangup detected on controlling terminal or death of controlling process\nSIGINT        2       Term    Interrupt from keyboard\nSIGQUIT       3       Core    Quit from keyboard\nSIGKILL       9       Term    Kill signal\nSIGUSR1   30,10,16    Term    User-defined signal 1\nSIGUSR2   31,12,17    Term    User-defined signal 2\n\u003c/code\u003e\u003c/pre\u003e\n\u003c/blockquote\u003e\n\u003cp\u003e总结下，最靠谱的写法就是直接用信号的字符描述啦。\u003ccode\u003ekill -s USR1 \u0026#x3C;PID\u003e\u003c/code\u003e\u003c/p\u003e\n\u003chr\u003e\n\u003ch3\u003e打印线程调用栈\u003c/h3\u003e\n\u003cp\u003e19 日下午再次重现，等到 20 日周一上班，总是成功地拿到了线程的调用栈。\u003c/p\u003e\n\u003cpre\u003e\u003ccode\u003e\"CP Server Thread-10\" tid=139694658537216\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at conn.communicate()(wsgiserver2.py:1532)\n    ... more omitted\n    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)\n    at return self.query(qout, processed=True)(db.py:720)\n    at self._db_execute(db_cursor, sql_query)(db.py:680)\n    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)\n    at out.write(x)(webapi.py:512)\n\n\"CP Server Thread-9\" tid=139694666929920\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at conn.communicate()(wsgiserver2.py:1532)\n    ... more omitted \n    at apps = list(db.select('application', vars, where='name=$name'))(xxx.py:149)\n    at return self.query(qout, processed=True)(db.py:720)\n    at self._db_execute(db_cursor, sql_query)(db.py:680)\n    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)\n    at out.write(x)(webapi.py:512)\n\n\"MainThread\" tid=139695478638400\n    at app.run()(xxx.py:326)\n    at return wsgi.runwsgi(self.wsgifunc(*middleware))(application.py:341)\n    at return httpserver.runsimple(func, server_addr)(wsgi.py:59)\n    at server.start()(httpserver.py:177)\n    at self.tick()(wsgiserver2.py:1956)\n    at s, addr = self.socket.accept()(wsgiserver2.py:2008)\n    at sock, addr = self._sock.accept()(socket.py:202)\n    at pystack()(pdbx.py:181)\n    at for filename, lineno, _, line in traceback.extract_stack(stack):(pdbx.py:169)\n\n... omit CP Server Thread-1 / Thread-2 / Thread-6 / Thread-7 / Thread-8\n... same as other thread\n\n\"CP Server Thread-4\" tid=139695180908288\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at conn.communicate()(wsgiserver2.py:1532)\n    ... more omitted \n    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)\n    at return self.query(qout, processed=True)(db.py:720)\n    at self._db_execute(db_cursor, sql_query)(db.py:680)\n    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)\n    at out.write(x)(webapi.py:512)\n\n\"APScheduler\" tid=139695219828480\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at self.__target(*self.__args, **self.__kwargs)(threading.py:765)\n    at self._event.wait(wait_seconds)(blocking.py:28)\n    at self.__cond.wait(timeout, balancing)(threading.py:622)\n    at waiter.acquire()(threading.py:339)\n\n\"CP Server Thread-3\" tid=139695189300992\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at conn.communicate()(wsgiserver2.py:1532)\n    ... more omitted \n    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)\n    at return self.query(qout, processed=True)(db.py:720)\n    at self._db_execute(db_cursor, sql_query)(db.py:680)\n    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)\n    at out.write(x)(webapi.py:512)\n\n\"CP Server Thread-5\" tid=139695172515584\n    at self.__bootstrap_inner()(threading.py:785)\n    at self.run()(threading.py:812)\n    at conn.communicate()(wsgiserver2.py:1532)\n    ... more omitted \n    at instances = list(db.select('instance', vars, where='app_name=$app_name and host=$host and port=$port'))(xxx.py:233)\n    at return self.query(qout, processed=True)(db.py:720)\n    at self._db_execute(db_cursor, sql_query)(db.py:680)\n    at print('%s (%s): %s' % (round(b-a, 2), self.ctx.dbq_count, str(sql_query)), file=debug)(db.py:623)\n    at out.write(x)(webapi.py:512)\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eOK，总计 10 个工作线程，全都阻塞在 \u003ccode\u003eout.write(x)\u003c/code\u003e ，多次打印调用栈结果相同。基本可以断定是 \u003ccode\u003ewrite\u003c/code\u003e 方法出了问题了。不过直到这个时候，都还是深陷在死锁原因中无法自拔（还是接触得太少了）。\u003c/p\u003e\n\u003cp\u003e虚度半个多钟... 后看代码了解到，其准备将 SQL 执行结果打印到标准错误。\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-python\"\u003edef _debugwrite(x):\n    try:\n        out = ctx.environ['wsgi.errors']\n    except:\n        out = sys.stderr\n    out.write(x)\ndebug.write = _debugwrite\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003e果断去查看 Python 服务的文件描述符 \u003ccode\u003elsof -p \u0026#x3C;PID\u003e\u003c/code\u003e / \u003ccode\u003els -al /proc/\u0026#x3C;PID\u003e/fd\u003c/code\u003e 。总算见着可信的证据了。\u003c/p\u003e\n\u003cpre\u003e\u003ccode\u003e\u003e lsof -p \u0026#x3C;PID\u003e\npython  139756 sysop    0r  FIFO     0,9       0t0 5210639 pipe\npython  139756 sysop    1w   REG   253,1      5187 1188500 /home/www/wwwroot/logs/eswitch-console.9999.log\npython  139756 sysop    2w  FIFO     0,9       0t0 5210641 pipe\npython  139756 sysop    3u  IPv4 5210787       0t0     TCP 10.1.5.60:65442-\u003e10.1.6.104:mysql (ESTABLISHED)\npython  139756 sysop    4r  FIFO     0,9       0t0 5210774 pipe\npython  139756 sysop    5w  FIFO     0,9       0t0 5210774 pipe\npython  139756 sysop    6r  FIFO     0,9       0t0 5210778 pipe\npython  139756 sysop    7w  FIFO     0,9       0t0 5210778 pipe\npython  139756 sysop    8u  IPv4 5210788       0t0     TCP *:distinct (LISTEN)\npython  139756 sysop    9u  IPv4 5226722       0t0     TCP localhost:distinct-\u003elocalhost:26032 (CLOSE_WAIT)\npython  139756 sysop   10u  IPv4 5226858       0t0     TCP localhost:distinct-\u003elocalhost:26052 (CLOSE_WAIT)\n... more omitted\n\u003c/code\u003e\u003c/pre\u003e\n\u003cpre\u003e\u003ccode\u003e\u003e ls -al /proc/\u0026#x3C;PID\u003e/fd\nlr-x------ 1 sysop sysop 64 May 20 13:47 0 -\u003e pipe:[5210639]\nl-wx------ 1 sysop sysop 64 May 20 13:47 1 -\u003e /home/path/to/logs/xxx.log\nl-wx------ 1 sysop sysop 64 May 20 13:47 2 -\u003e pipe:[5210641]\nlrwx------ 1 sysop sysop 64 May 20 13:47 3 -\u003e socket:[5210787]\nlr-x------ 1 sysop sysop 64 May 20 13:47 4 -\u003e pipe:[5210774]\nl-wx------ 1 sysop sysop 64 May 20 13:47 5 -\u003e pipe:[5210774]\nlr-x------ 1 sysop sysop 64 May 20 13:47 6 -\u003e pipe:[5210778]\nl-wx------ 1 sysop sysop 64 May 20 13:47 7 -\u003e pipe:[5210778]\n... more omitted\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003e标准错误(fd = 2)指向了一个匿名管道（inode = 5210641）。但是找遍整个系统都没有这个匿名管道的读取方，只有写入方\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-sh\"\u003e\u003e sudo lsof | grep 5210641\nbash      139747          sysop    2w     FIFO                0,9       0t0    5210641 pipe\npython    139756          sysop    2w     FIFO                0,9       0t0    5210641 pipe\npython    139756 139764   sysop    2w     FIFO                0,9       0t0    5210641 pipe\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003eOK，合理的解释出现了。管道的缓冲区大小有限(经过测试是 64KB)，Python 服务在不断地向标准错误打印日志，从而导致匿名管道(inode = 5210641)的缓冲区数据不断积累，最终达到满的状态。这个过程大概需要一天多的心跳包才能积累得到。而系统调用 \u003ccode\u003ewrite\u003c/code\u003e 发现标准错误对应的文件已满，为等待 IO 就绪而陷入睡眠状态。同时，Main 线程在不断地 Accept 新的套接字的建立，而没有更多工作线程来处理新的请求，Nginx 因为连接超时直接发出来 FIN 包。最后，积累了几千/上万请求的 Python 服务也没法主动 close 已有的套接字（即 FIN,ACK 包因为没法发送而在本机不断积累 \u003ccode\u003eCLOSE_WAIT\u003c/code\u003e 状态的连接）\u003c/p\u003e\n\u003ch3\u003e重定向标准错误的原因\u003c/h3\u003e\n\u003cp\u003e至于为何会将标准错误重定向到一个匿名管道呢？百思不得其解，不过最后还是从应用负责人那儿得到了提示。新的发布方式采用了全新的启动命令:\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-sh\"\u003essh -fn xx.xx.x.60 'cd /home/path/to/xxx ; python -u xxx.py 8080 \u003e\u003e /home/path/to/logs/xxx.log'\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003e一看就能和前面的原因衔接，使用 ssh 直接调用命名，不会建立一个终端，由 ssh 远程命令启动的任务，其标准输入/输出/错误默认将会通过管道重定向的 ssh server 端，并通过网络传回发起的 ssh client 端。\u003c/p\u003e\n\u003cp\u003e\u003cem\u003e以发起 \u003ccode\u003essh -fn ...\u003c/code\u003e 的机器为 xx.192，目标机器为 xx.60\u003c/em\u003e\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-plain\"\u003e  xx.192                       |           xx.60\n  -----------------------------+-------------------------------\n                               | \n    ssh client                 |          ssh serve           python serve\n  +------------+               |        +------------+       +-------------+\n  | 0 | stdin  |               |        | y | pipe[a]| \u0026#x3C;---\u003e | 0 | pipe[a] |\n  | 1 | stdout |               |        | z | pipe[b]| \u0026#x3C;-+   | 1 | xxx.log |\n  | 2 | stderr |               |        |   |        |   +-\u003e | 2 | pipe[b] |\n  | ...        |               |        | ...        |       | ...         |\n  | x | sock   | \u0026#x3C;--------------------\u003e | w | sock   |       | ...         |\n  +------------+               |        +------------+       +-------------+\n\u003c/code\u003e\u003c/pre\u003e\n\u003cp\u003ePython 服务通过管道与 ssh serve 进行进程间交互，最终会将标准错误打印到 192 机器的标准输出/错误上（一般是终端，也就是我们将在终端上看到 Python 服务的错误日志）。而问题在于 ssh serve 任务被杀掉了，从而 \u003ccode\u003epipe[b]\u003c/code\u003e 只能不断地向匿名管道写入数据，而没有任务读取数据，一天多时间也就将缓冲区写满了。\u003c/p\u003e\n\u003ch2\u003e总结\u003c/h2\u003e\n\u003cp\u003e到此为止，问题总算得到了圆满的解释，历时 5 天。最重要的就是通过调用栈定位代码阻塞的原因，否则就真是瞎找。对于匿名管道问题的发现、write 系统调用导致的线程睡眠，都是建立在调用栈信息之上的定向探究的过程。\u003c/p\u003e\n\u003cpre\u003e\u003ccode class=\"language-plain\"\u003e  __                    __                  \n / _| __ _ _ __   __ _ / _| ___ _ __   __ _ \n| |_ / _` | '_ \\ / _` | |_ / _ \\ '_ \\ / _` |\n|  _| (_| | | | | (_| |  _|  __/ | | | (_| |\n|_|  \\__,_|_| |_|\\__, |_|  \\___|_| |_|\\__, |\n                 |___/                |___/ \n\u003c/code\u003e\u003c/pre\u003e"},"buildId":"KZWxx6ur1oSf8xr-9UZXm","dynamicBuildId":false,"assetPrefix":"https://www.ffutop.com/blog","nextExport":true}</script><script async="" id="__NEXT_PAGE__/post" src="https://www.ffutop.com/blog/_next/static/KZWxx6ur1oSf8xr-9UZXm/pages/post.js"></script><script async="" id="__NEXT_PAGE__/_app" src="https://www.ffutop.com/blog/_next/static/KZWxx6ur1oSf8xr-9UZXm/pages/_app.js"></script><script src="https://www.ffutop.com/blog/_next/static/runtime/webpack-8ed9452df514b4d17d80.js" async=""></script><script src="https://www.ffutop.com/blog/_next/static/chunks/commons.7e5e68e72610ac3a4255.js" async=""></script><script src="https://www.ffutop.com/blog/_next/static/chunks/styles.f3603d0a56c82c4f5e78.js" async=""></script><script src="https://www.ffutop.com/blog/_next/static/runtime/main-fd73dbd6f398b7b886ec.js" async=""></script></body></html>